### ISSUE TITLE
Raising a couple issues with lab completion

### ISSUE THREAD

**Issue by amyjoscelyn** [learn-co-curriculum/git-todo#7]
@misterfifths @markedwardmurray

I can't finish this lab.  I already have the ssh key connected to Git but didn't know that when I started.  Also it said git-todo repository already existed so I couldn't create it through Git.

**Comment by markedwardmurray** [comment]
^ ios-0915 student

**Comment by pletcher** [comment]
I'm going to close this, as it looks like this was toggled to a README and so shouldn't prevent students from proceeding.
